server:
  port: 8086

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/reservation_service_db?createDatabaseIfNotExist=true
    username: root
    password: password

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
#        format_sql: true

  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER