server:
  port: 8086
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/reservation_service_db?createDatabaseIfNotExist=true
    username: root
    password: password

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format-sql: true

  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER